site_name: My Java Code Documentation
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Java Code:
      - java_1: java-code.md
      - java_2: java_2.md
      - java_3: java_3.md    # أضف هذا السطر هنا

# This is where MKDocs looks for the markdown files
docs_dir: docs_src
